spring.application.name=spring-ai-nsfw
#
spring.ai.openai.api-key=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

#Chat model
spring.ai.openai.chat.model=gpt-5.4
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.max-tokens=8192
spring.ai.openai.embedding.options.dimensions=768

# Embedding model
spring.ai.openai.embedding.options.model=text-embedding-3-small


# Enable moderation
spring.ai.openai.moderation.enabled=true

# Latest text validation
spring.ai.openai.moderation.model=omni-moderation-latest